"""add_raw_text_harvard_to_resumes

Revision ID: dac55688d5c4
Revises: e5f2a1c9d8b7
Create Date: 2026-10-10 08:38:42.122403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac55688d5c4'
down_revision: Union[str, Sequence[str], None] = 'e5f2a1c9d8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text_harvard', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text_harvard')
    # ### end Alembic commands ###
